Dpnp diag
IntelPython/numba-dpex pull request #414
Opened 2021-05-31 20:08 UTC by Rubtsowa

2021-06-18 13:27 UTC, PokhodenkoSA approved these changes

2021-12-07 07:37 UTC, PokhodenkoSA requested changes
Does not work now. Requires debugging.

2022-10-28 23:38 UTC, chudur-budur reviewed
Looks good, but some improvements can be done.

If you could "Allow edits from maintainers", we can rebase on the current main and test it. 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Also, it would be great if you could squash multiple commits into one.
https://www.scraggo.com/how-to-squash-commits/

2022-10-28 23:38 UTC, chudur-budur commented on numba_dppy/dpnp_glue/dpnp_array_creations_impl.py
> +            shape_result = (n,)
Why don't we just do like
```python
if v.ndim < 1:
    raise ValueError("ndim has to be nonempty, i.e. >= 1")
elif v.ndim == 1:
    # do for ndim == 1
else:
    # do for ndim > 1  
```

2022-10-28 23:38 UTC, chudur-budur commented on numba_dppy/dpnp_glue/dpnp_array_creations_impl.py
> +                n = 0
If `k > 0`, `v.shape[0] - k` will be the minimum. Again if `k < 0`, `v.shape[0] + k` will be the minimum. Therefore, why don't we do like:
```python
n = v.shape[0] - k if k > 0 else v.shape[0] + k  
```
or we can just do simply like
```python
p,q = v.shape[0] - k, v.shape[0] + k
n = (p if p > 0 else 0) if k > 0 else (q if q < 0 else 0)
```

2022-10-29 04:49 UTC, chudur-budur commented on numba_dppy/dpnp_glue/dpnp_array_creations_impl.py
> +            shape_result = (n,)
Also if `k > 0`, `v.shape[0] - k` will be the minimum. Again if `k < 0`, `v.shape[0] + k` will be the minimum. Therefore, why don't we do like:
```python
if k > 0:
    n = v.shape[0] if v.shape[0] <= v.shape[1] - k else v.shape[1] - k
else:
    n = v.shape[1] if v.shape[1] <= v.shape[0] + k else v.shape[0] + k  
```

2023-03-06 04:32 UTC, diptorupd commented
The code is too out of date by now.

2023-03-06 04:32 UTC, closed without merging